### ISSUE TITLE
Atualizar READ ME do repositório

### ISSUE THREAD

**Issue by erivanbarbosa** [erivanbarbosa/BrechoDosLivros#6]
Preencher o documento READ ME do repositório, descrevendo o problema e fornecendo links e/ou informações úteis.

Vou deixar aqui três links que podem ajudar nesta tarefa:

O primeiro é o endereço de um github que apresenta diversos exemplos de bons arquivos READ ME existentes no github
https://github.com/matiassingers/awesome-readme

O segundo é um template, que talvez possa ajudar, embora seja muito engessado
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

Deixarei um ultimo com mais alguns exemplos
https://courses.cs.washington.edu/courses/cse326/02wi/homework/hw5/README-1.txt

**Comment by caionaweb** [comment]
README.md em processo de atualização
